import streamlit as st
import os
from pathlib import Path
import streamlit.components.v1 as components

# Configure application
st.set_page_config(
    page_title="Quantitative Strategies Dashboard",
    page_icon="📈",
    layout="wide"
)

st.title("📈 Quantitative Strategies Dashboard")
st.markdown("Visualize and compare backtest reports generated by all trading strategies.")

# Ensure the reports directory exists
REPORTS_DIR = Path("strategies/reports")
if not REPORTS_DIR.exists():
    st.error(f"Reports directory not found at {REPORTS_DIR.absolute()}")
    st.stop()

# Load all reports into a generic data structure
reports_data = []

# 1. Parse markdown summaries
md_files = list(REPORTS_DIR.glob("*_report.md"))
for file in md_files:
    filename = file.name
    if filename == "comparison_report.md":
        reports_data.append({
            "strategy": "Overview", 
            "ticker": "ALL", 
            "path": file,
            "type": "markdown"
        })
        continue
    
    # Filename format: {strategy_name_and_version}_{ticker}_report.md
    base = filename.replace("_report.md", "")
    parts = base.rsplit("_", 1)
    
    if len(parts) == 2:
        strategy_name = parts[0].replace("_", " ").title()
        ticker = parts[1].upper()
        reports_data.append({
            "strategy": strategy_name, 
            "ticker": ticker, 
            "path": file,
            "type": "markdown"
        })
    else:
        # Fallback if the name doesn't follow the pattern
        reports_data.append({
            "strategy": base.title(), 
            "ticker": "UNKNOWN", 
            "path": file,
            "type": "markdown"
        })

# 2. Parse HTML portfolio dashboards
html_files = list(REPORTS_DIR.glob("*.html"))
for file in html_files:
    if file.name == "portfolio_dashboard.html":
        reports_data.append({
            "strategy": "Portfolio Dashboard", 
            "ticker": "ALL", 
            "path": file,
            "type": "html"
        })

# Check if we have any reports
if not reports_data:
    st.info("No reports found in the strategies/reports/ directory.")
    st.stop()

# --- SIDEBAR UI ---
st.sidebar.header("🔍 Filters")

# Strategy selection
strategies = sorted(list(set(d["strategy"] for d in reports_data)))
# Move "Overview" and "Portfolio Dashboard" to the top if they exist
for top_item in ["Portfolio Dashboard", "Overview"]:
    if top_item in strategies:
        strategies.remove(top_item)
        strategies.insert(0, top_item)

selected_strategy = st.sidebar.selectbox("Select Strategy / View", strategies)

# Filter underlying data by strategy
filtered_data = [d for d in reports_data if d["strategy"] == selected_strategy]

# Ticker selection (only show if there are multiple tickers for this strategy)
tickers = sorted(list(set(d["ticker"] for d in filtered_data)))
if len(tickers) > 1 or (len(tickers) == 1 and tickers[0] != "ALL"):
    selected_ticker = st.sidebar.selectbox("Select Ticker", tickers)
else:
    selected_ticker = tickers[0]

# --- MAIN PAGE RENDERING ---
# Get the specific file path based on selection
selected_report = next((d for d in filtered_data if d["ticker"] == selected_ticker), None)

st.divider()

if selected_report and selected_report["path"].exists():
    path = selected_report["path"]
    report_type = selected_report["type"]
    
    if report_type == "markdown":
        try:
            with open(path, "r", encoding="utf-8") as f:
                content = f.read()
            # Render markdown using Streamlit
            st.markdown(content)
        except Exception as e:
            st.error(f"Error reading {path.name}: {e}")
            
    elif report_type == "html":
        try:
            with open(path, "r", encoding="utf-8") as f:
                html_data = f.read()
            # Embed HTML with 1000px height and scroll bar
            components.html(html_data, height=1000, scrolling=True)
        except Exception as e:
            st.error(f"Error loading HTML file {path.name}: {e}")
else:
    st.error("Report file not found or could not be loaded.")
